const {app}=require('electron')
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict')
const {createWindow}=require('../../electron/window.cjs')
const {SQLiteService,openFormalDatabase,DesktopDataService,MigrationManager,BUSINESS_METHODS,MIGRATION_METHODS}=require('../../.electron-main/sqlite-service.cjs')
const directory=fs.mkdtempSync(path.join(app.getPath('temp'),'yaya-billing-1.1-')),file=path.join(directory,'formal.db')
app.setPath('userData',directory)
let service,ipc,migration,win
let now=Date.now(),base=now
const wait=ms=>new Promise(r=>setTimeout(r,ms))
async function until(expression){for(let i=0;i<100;i++){const value=await win.webContents.executeJavaScript(expression);if(value)return value;await wait(100)}throw Error('检查超时：'+expression)}
app.whenReady().then(async()=>{
  const initial=openFormalDatabase(file,true);initial.close();service=new SQLiteService(file,{clock:()=>now})
  migration=new MigrationManager(directory,file,'sqlite');ipc=require('../../electron/ipc.cjs').registerDataIPC(new DesktopDataService(service,migration),[...BUSINESS_METHODS,...MIGRATION_METHODS])
  const created=createWindow({show:false,storageMode:'sqlite',indexFile:path.resolve('dist/index.html'),beforeLoad:(w,target)=>ipc.attach(w,target)});win=created.win;await created.ready
  await until("document.body.textContent.includes('日常工作台')")
  const execute=js=>win.webContents.executeJavaScript(js,true)
  async function call(group,method,...args){const result=await execute(`window.yayaDesktop.repositories.${group}.${method}(...${JSON.stringify(args)})`);if(!result.ok)throw Error(result.message);return result.value}
  await execute(`window.__plays=[];window.__clock=${base};Date.now=()=>window.__clock;HTMLMediaElement.prototype.play=function(){window.__plays.push(this.src);return Promise.resolve()};true`)
  for(const name of ['balance-warning-5min','balance-depleted']) {
    const loaded=await execute(`new Promise(resolve=>{const audio=new Audio('./sounds/${name}.m4a');audio.onloadedmetadata=()=>resolve(audio.duration>0);audio.onerror=()=>resolve(false);audio.load()})`)
    assert.equal(loaded,true,'本地录音能够解码：'+name)
  }
  const boss=await call('bosses','create',{id:'BALANCE-ALERT',nickname:'提示音测试',hourlyRateCents:3500,notes:''});await call('balances','changeBalance',boss.id,{type:'recharge',amountCents:875,notes:''});const order=await call('orders','start',boss.id)
  await until("document.body.textContent.includes('实时预计余额')")
  const changes=service.database.prepare('SELECT total_changes() AS n').get().n
  now=base+601000;await execute(`window.__clock=${now}`)
  await until("window.__plays.length===1 && document.body.textContent.includes('余额即将不足')")
  assert.ok((await execute('window.__plays[0]')).endsWith('/sounds/balance-warning-5min.m4a'))
  await wait(1200);assert.equal(await execute('window.__plays.length'),1)
  now=base+900000;await execute(`window.__clock=${now}`)
  await until("window.__plays.length===2 && document.body.textContent.includes('老板余额已用完，当前进入超时服务')")
  await wait(2300);assert.equal(await execute('window.__plays.length'),2)
  assert.equal(service.database.prepare('SELECT total_changes() AS n').get().n,changes)
  assert.equal(service.snapshot().entries.length,1);assert.equal(service.snapshot().bosses[0].balanceCents,875)
  await call('orders','pause',order.id);now+=600000;await execute(`window.__clock=${now}`);await wait(1200)
  assert.equal(await execute('window.__plays.length'),2);assert.equal(service.snapshot().orders[0].status,'paused')
  await call('balances','changeBalance',boss.id,{type:'recharge',amountCents:875,notes:'充值重新提醒'})
  await until("!document.body.textContent.includes('老板余额已用完')")
  await call('orders','resume',order.id);await wait(1200);now+=900000;await execute(`window.__clock=${now}`)
  await until('window.__plays.length===3');await wait(2200);assert.equal(await execute('window.__plays.length'),3)
  assert.equal(service.snapshot().entries.length,2)
  fs.writeFileSync(path.resolve('.electron-smoke/balance-alert-1.1.png'),(await win.webContents.capturePage()).toPNG())
  const done=await call('orders','complete',order.id);assert.equal(done.finalChargeCents,1750);assert.equal(done.balanceAtEndCents,0);assert.equal(service.snapshot().entries.filter(e=>e.type==='order_consumption').length,1)
  assert.equal(await execute("document.querySelector('[role=switch]').checked"),true)
  await execute("document.querySelector('[role=switch]').click();true")
  await call('balances','changeBalance',boss.id,{type:'recharge',amountCents:875,notes:'静音测试'})
  const muted=await call('orders','start',boss.id)
  await until("document.body.textContent.includes('实时预计余额')")
  now+=601000;await execute(`window.__clock=${now}`)
  await until("document.body.textContent.includes('余额即将不足')")
  assert.equal(await execute('window.__plays.length'),3)
  now+=299000;await execute(`window.__clock=${now}`)
  await until("document.body.textContent.includes('老板余额已用完')")
  assert.equal(await execute('window.__plays.length'),3)
  await execute("document.querySelector('[role=switch]').click();true")
  await wait(1200);assert.equal(await execute('window.__plays.length'),3)
  await execute("document.querySelector('[role=switch]').click();true")
  await call('orders','pause',muted.id)
  const reloaded=new Promise(resolve=>win.webContents.once('did-finish-load',resolve));win.reload();await reloaded
  await until("document.querySelector('[role=switch]')")
  assert.equal(await execute("document.querySelector('[role=switch]').checked"),false)
  await until("document.body.textContent.includes('老板余额已用完')")
  await call('orders','complete',muted.id)
  console.log('Electron正式计费与设置通过：期间零数据库写入；本地录音、静音保留文字、开启不补播、刷新后偏好保留。')
  await wait(200);win.destroy();await ipc.whenIdle();ipc.dispose();migration.dispose();service.close();app.exit(0)
}).catch(error=>{console.error(error);win?.destroy();ipc?.dispose();migration?.dispose();service?.close();app.exit(1)})
