import './style.css'
import { screenshotMarkup, setupScreenshotViewer } from './screenshots.js'
import { site, assetUrl } from './config.js'
import { features, tutorials } from './content.js'
const escape = text => String(text).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const icon = '<svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5" stroke-linecap="round" stroke-linejoin="round"/></svg>'
const download = extra => `<a class="download ${extra || ''}" href="${escape(assetUrl(site.download.url))}" ${site.download.available ? `download="${escape(site.download.filename)}"` : ''} data-download>${icon}点击下载丫丫的陪玩日记</a>`
document.querySelector('#app').innerHTML = `
<a class="skip-link" href="#main">跳到主要内容</a>
<header class="topbar"><a href="#" class="brand"><img src="${assetUrl(site.brand)}" alt="丫丫品牌头像" width="36" height="36"><span>${site.name}</span></a><nav aria-label="官网导航"><a href="#features">主要功能</a><a href="#tutorial">使用教程</a><a class="nav-download" href="#download">下载软件 ↗</a></nav></header>
<main id="main">
<section class="hero" id="download"><div class="eyebrow"><span></span> 给日常陪伴，一个认真记录的地方</div><img class="hero-avatar" src="${assetUrl(site.brand)}" width="78" height="78" alt="丫丫的陪玩日记头像"><h1>${site.name}</h1><p class="hero-copy">陪玩计时、余额管理、打赏记录和每日账单，<br class="desktop-break">一本帮你把每一份陪伴认真记下来的小日记。</p>${download()}<div class="download-meta"><span>Windows 11 / Windows 10</span><i>·</i><span>Portable 版本 · v${site.version}</span></div><p class="small muted">无需安装 · 解压即可使用</p><p class="download-tip">第一次使用请先完整解压 ZIP，再运行 <code>YayaDiary.exe</code>。</p><p class="release-note" role="status" id="download-status">${site.download.available ? '资料保存在你的电脑，不需要注册账号。' : '下载文件正在准备中。发布后可在这里获取。'}</p></section>
<section class="preview" aria-label="软件工作台示意"><div class="preview-bar"><span class="window-dots"><i></i><i></i><i></i></span><span>丫丫的陪玩日记</span><span class="preview-label">界面示意</span></div><div class="preview-body"><aside class="preview-sidebar"><img src="${assetUrl(site.brand)}" alt="" width="40" height="40"><strong>丫丫的小日记</strong><span class="selected">◉ 首页概览</span><span>♡ 老板信息</span><span>▤ 收入统计</span><span>▧ 数据管理</span><small>陪伴有记录，心里有底。</small></aside><div class="preview-main"><div class="preview-heading"><div><small>每一份陪伴，都值得被记住</small><h2>日常工作台</h2></div><span class="preview-pill">本机保存</span></div><div class="preview-order"><div class="section-row"><strong>当前订单</strong><span class="active-badge">● 进行中</span></div><div class="demo-metrics"><div><small>已服务时间</small><b class="timer">00:12:00</b></div><div><small>实时消费</small><b>¥7.00</b></div><div><small>实时预计余额</small><b>¥63.00</b></div></div><div class="demo-bottom"><span>老板：YAYA-01 丫丫<br><small>本单单价 ¥35.00 / 小时</small></span><span class="demo-buttons">暂停　　结束订单</span></div></div><div class="demo-quick"><strong>快捷操作</strong><div><span>＋ 开始订单</span><span>↗ 老板充值</span><span>♡ 记录打赏</span></div></div></div></div></section>
<section class="section" id="features"><div class="section-intro"><span class="kicker">轻轻松松，安排好每一天</span><h2>该记下的，都在这里。</h2><p>从开始陪玩，到整理账单。少一点手忙脚乱，多一点安心。</p></div><div class="feature-grid">${features.map(([number,title,copy])=>`<article class="feature-card"><span class="feature-icon">${number}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div></section>
<section class="section tutorial" id="tutorial"><div class="section-intro"><span class="kicker">第一次使用也没关系</span><h2>使用教程</h2><p>跟着这 16 个小步骤，从下载到记好第一笔账。</p></div><div class="tutorial-layout"><nav class="tutorial-nav" aria-label="教程目录"><strong>从这里开始</strong>${tutorials.map((t,i)=>`<a href="#step-${i+1}"><span>${String(i+1).padStart(2,'0')}</span>${t.title}</a>`).join('')}</nav><div class="tutorial-steps">${tutorials.map((t,i)=>`<article class="tutorial-step ${t.warning?'warning-step':''}" id="step-${i+1}"><div class="step-heading"><span class="step-number">${String(i+1).padStart(2,'0')}</span><div><small>${t.group}</small><h3>${t.title}</h3></div></div><ol>${t.lines.map(line=>`<li>${escape(line.replace('{filename}',site.download.filename))}</li>`).join('')}</ol>${t.path?`<code class="path">${escape(t.path)}</code>`:''}${screenshotMarkup(t,escape)}</article>`).join('')}</div></div></section>
<section class="closing"><span class="kicker">认真陪伴，也认真记账</span><h2>下一次开局，就从这里开始。</h2>${download()}<p class="small muted">Windows 10 / 11 · Portable · v${site.version}</p></section>
</main><footer><span>${site.name} · v${site.version}</span><span>Made for everyday companion work.</span><a href="#download">回到顶部 ↑</a></footer>`
for (const button of document.querySelectorAll('[data-download]')) button.addEventListener('click', event => {
  if (!site.download.available) { event.preventDefault(); const status=document.querySelector('#download-status');status.textContent='下载文件尚未发布，请联系软件提供者获取。'; status.scrollIntoView({behavior:'smooth',block:'center'}) }
})

setupScreenshotViewer()
