import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import { SQLiteService } from '../electron/sqlite/service.ts'
import { migrations } from '../electron/sqlite/schema.ts'
import { importState, reconcile, openFormalDatabase } from '../electron/sqlite/migration.ts'
import { BackupManager } from '../electron/sqlite/maintenance.ts'
import { AutoBackupManager } from '../electron/sqlite/autoBackup.ts'
import { buildDailyWorkbook } from '../electron/sqlite/dailyExport.ts'
import { calculateStatistics, periodRange } from '../src/features/statistics/statistics.ts'
import { createLocalStorageDataAccess } from '../src/features/storage/localStorageDataAccess.ts'
import type { Boss } from '../src/features/bosses/types'
import type { Order } from '../src/features/orders/types'
import type { BusinessMethod } from '../electron/sqlite/service.ts'
import type { TestContext } from 'node:test'
function fixture(t: TestContext) {
  let now = new Date(2026,9,8,12).getTime(), failure = false
  const service = new SQLiteService(':memory:', { clock:()=>now, checkpoint:()=>{if(failure)throw Error('故障')} })
  t.after(()=>service.close())
  const call = <T,>(method: BusinessMethod,...args:unknown[])=>service.execute(method,args) as T
  const create=(id:string,isTestMode?:boolean)=>call<Boss>('bosses.create',{id,nickname:'丫丫',hourlyRateCents:3500,notes:'',isTestMode})
  const recharge=(id:string)=>call('balances.changeBalance',id,{type:'recharge',amountCents:7000,notes:''})
  const work=(id:string)=>{recharge(id);const o=call<Order>('orders.start',id);now+=600000;call('orders.pause',o.id);now+=300000;call('orders.resume',o.id);now+=780000;call('orders.complete',o.id);const b=service.snapshot().bosses.find(b=>b.id===id)!;call('tips.create',b.profileId,{amountCents:2000,receivedAt:new Date(now).toISOString(),notes:''})}
  return {service,call,create,recharge,work,now:()=>now,fail:()=>{failure=true}}
}
test('测试模式默认关闭，新建可开启，未产生记录可切换',t=>{const f=fixture(t);assert(!f.create('A').isTestMode);const b=f.create('B',true);assert(b.isTestMode);assert.equal(f.call('bosses.modeLocked','B'),false);assert(!f.call<Boss>('bosses.update','B',{nickname:'丫丫',hourlyRateCents:3500,notes:'',isTestMode:false}).isTestMode)})
test('测试模式完整充值、暂停继续、最终结算、打赏，保留历史',t=>{const f=fixture(t);f.create('A',true);f.work('A');const s=f.service.snapshot();assert.equal(s.orders[0].accumulatedMs,1380000);assert.equal(s.orders[0].finalChargeCents,1342);assert.equal(s.entries.length,2);assert.equal(s.tips.length,1);assert([...s.orders,...s.entries,...s.tips].every(r=>r.isTestMode))})
for(const period of ['today','week','month'] as const)test(`测试订单、充值、打赏和有效时长排除${period}正式统计`,t=>{const f=fixture(t);f.create('A',true);f.work('A');const stats=calculateStatistics(f.service.snapshot(),periodRange(period,f.now()));assert.deepEqual(stats,{serviceMs:0,serviceIncomeCents:0,rechargeCents:0,tipCents:0,receiptsCents:0,incomeCents:0})})
test('正式统计保持原有算法，Excel所有sheet排除测试记录及订单数量',t=>{const f=fixture(t);f.create('TEST',true);f.work('TEST');f.create('FORMAL');f.work('FORMAL');const s=f.service.snapshot(),stats=calculateStatistics(s,periodRange('today',f.now()));assert.equal(stats.serviceMs,1380000);assert.equal(stats.incomeCents,3342);assert.equal(stats.rechargeCents,7000);const book=buildDailyWorkbook(s,'2026-10-08',f.now());assert.equal(book.getWorksheet('订单记录')!.rowCount,2);assert.equal(book.getWorksheet('余额流水')!.rowCount,3);assert.equal(book.getWorksheet('打赏记录')!.rowCount,2);assert.equal(book.getWorksheet('每日概览')!.getCell('G2').value,1);for(const sheet of book.worksheets)sheet.eachRow(row=>assert(!JSON.stringify(row.values).includes('TEST')))})
for(const source of ['订单','流水','打赏'])test(`${source}产生后锁定测试模式，删除打赏也不解锁`,t=>{const f=fixture(t),b=f.create('A',true);if(source==='订单'){f.recharge('A');f.call('orders.start','A')}else if(source==='流水')f.recharge('A');else{const tip=f.call<{id:string}>('tips.create',b.profileId,{amountCents:100,receivedAt:new Date(f.now()).toISOString(),notes:''});f.call('tips.remove',tip.id)}assert.equal(f.call('bosses.modeLocked','A'),true);assert.throws(()=>f.call('bosses.update','A',{nickname:'丫丫',hourlyRateCents:4000,notes:'',isTestMode:false}),/无法再切换/);assert.equal(f.call<Boss>('bosses.update','A',{nickname:'丫丫',hourlyRateCents:4000,notes:''}).isTestMode,true)})
test('删除测试资料后历史仍排除统计，重建同ID为独立正式身份',t=>{const f=fixture(t),old=f.create('A',true);f.work('A');f.call('bosses.remove','A');assert.equal(calculateStatistics(f.service.snapshot(),periodRange('today',f.now())).incomeCents,0);const fresh=f.create('A');assert.notEqual(fresh.profileId,old.profileId);assert(!fresh.isTestMode);f.work('A');assert.equal(calculateStatistics(f.service.snapshot(),periodRange('today',f.now())).incomeCents,3342)})
test('清空测试身份、暂停区间、历史、流水、打赏；正式数据逐字段完全不变',t=>{const f=fixture(t);f.create('TEST',true);f.work('TEST');f.call('bosses.remove','TEST');f.create('FORMAL');f.work('FORMAL');const before=f.service.snapshot();f.call('testing.clear');const after=f.service.snapshot();assert.deepEqual(after,{...before,orders:before.orders.filter(r=>!r.isTestMode),entries:before.entries.filter(r=>!r.isTestMode),tips:before.tips.filter(r=>!r.isTestMode)});assert.equal(f.service.database.prepare('SELECT count(*) n FROM boss_identities').get()!.n,1);assert.equal(f.service.database.prepare('PRAGMA foreign_key_check').all().length,0)})
test('清空测试数据事务失败全部回滚',t=>{const f=fixture(t);f.create('A',true);f.work('A');const before=f.service.snapshot();f.fail();assert.throws(()=>f.call('testing.clear'),/故障/);assert.deepEqual(f.service.snapshot(),before)})
test('清空测试进行中订单不影响正式老板',t=>{const f=fixture(t);f.create('F');f.recharge('F');f.create('T',true);f.recharge('T');f.call('orders.start','T');f.call('testing.clear');assert.equal(f.service.snapshot().orders.length,0);assert.equal(f.service.snapshot().bosses[0].id,'F');assert.equal(f.service.snapshot().bosses[0].balanceCents,7000)})
test('旧schema4升级到5，旧资料默认正式且历史记录锁定属性',t=>{const dir=mkdtempSync(join(tmpdir(),'yaya-mode-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const file=join(dir,'old.db'),db=new DatabaseSync(file);db.exec('CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at INTEGER NOT NULL) STRICT');for(const m of migrations.filter(m=>m.version<=4)){db.exec(m.sql);db.prepare('INSERT INTO schema_migrations VALUES (?,?,?)').run(m.version,m.name,Date.now())}db.prepare('INSERT INTO boss_identities VALUES (?,?,?)').run('old','A',1);db.prepare('INSERT INTO boss_profiles VALUES (?,?,?,?,?,?,?)').run('old','A','丫丫',3500,0,1,'');db.close();const service=new SQLiteService(file);try{const b=service.snapshot().bosses[0];assert.equal(b.profileId,'old');assert(!b.isTestMode);assert.equal(service.database.prepare('SELECT MAX(version) v FROM schema_migrations').get()!.v,5)}finally{service.close()}})
test('SQLite在线自动备份包含测试身份和完整记录',async t=>{const dir=mkdtempSync(join(tmpdir(),'yaya-mode-backup-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const file=join(dir,'formal.db'),service=openFormalDatabase(file,true),manager=new BackupManager({service},file,dir,'1.2.0');try{const b=service.execute('bosses.create',[{id:'YAYA-01',nickname:'丫丫',hourlyRateCents:3500,notes:'',isTestMode:true}]) as Boss;service.execute('balances.changeBalance',[b.id,{type:'recharge',amountCents:7000,notes:''}]);const auto=new AutoBackupManager(manager,dir,'sqlite');await auto.run();const fs=await import('node:fs');const names=fs.readdirSync(join(dir,'backups','auto')).filter(n=>n.endsWith('.db'));assert.equal(names.length,1);const saved=new SQLiteService(join(dir,'backups','auto',names[0]));try{assert.deepEqual(saved.snapshot(),service.snapshot());assert.equal(saved.database.prepare('PRAGMA integrity_check').get()!.integrity_check,'ok')}finally{saved.close()}}finally{manager.dispose();service.close()}})
test('localStorage兼容路径保留模式并只清理测试身份',async()=>{const map=new Map<string,string>(),storage={getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v)},removeItem:(k:string)=>{map.delete(k)}};const access=createLocalStorageDataAccess({storage:()=>storage});await access.bosses.create({id:'T',nickname:'丫丫',hourlyRateCents:3500,notes:'',isTestMode:true});await access.bosses.create({id:'F',nickname:'丫丫',hourlyRateCents:3500,notes:''});await access.balances.changeBalance('T',{type:'recharge',amountCents:7000,notes:''});assert.equal(calculateStatistics(await access.statistics.read(),periodRange('today')).rechargeCents,0);await access.testing.clear();assert.equal((await access.bosses.list())[0].id,'F')})

test('迁移测试历史、删除身份和同ID重建后，属性与对账保持一致',t=>{const f=fixture(t);f.create('A',true);f.work('A');f.call('bosses.remove','A');f.create('A');f.work('A');const target=new SQLiteService(':memory:');t.after(()=>target.close());const file={format:'yaya-diary-migration' as const,formatVersion:1 as const,dataVersion:3 as const,capturedAt:f.now(),rawKeys:{},data:f.service.snapshot(),fingerprint:'test-mode-roundtrip'};importState(target,file);assert.deepEqual(target.snapshot(),f.service.snapshot());assert.equal(reconcile(file,target).passed,true);target.execute('testing.clear');assert.equal(target.snapshot().bosses[0].id,'A');assert.equal(target.snapshot().orders.length,1)})
