const {app,BrowserWindow}=require('electron')
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict')
app.setPath('userData',fs.mkdtempSync(path.join(app.getPath('temp'),'yaya-website-check-')))
app.whenReady().then(async()=>{
  const output=path.resolve('website/.checks');fs.mkdirSync(output,{recursive:true})
  const win=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true}})
  const errors=[];win.webContents.on('console-message',event=>{if(event.level==='error')errors.push(event.message)})
  await win.loadURL('http://127.0.0.1:5180/');await win.webContents.executeJavaScript('document.fonts.ready');await new Promise(r=>setTimeout(r,200))
  const check=()=>win.webContents.executeJavaScript(`({title:document.querySelector('h1').textContent,features:document.querySelectorAll('.feature-card').length,steps:document.querySelectorAll('.tutorial-step').length,images:document.querySelectorAll('.screenshot-placeholder').length,link:document.querySelector('[data-download]').getAttribute('href'),overflow:document.documentElement.scrollWidth>innerWidth,brand:document.querySelector('.hero-avatar').naturalWidth>0})`)
  const desktop=await check();assert.equal(desktop.title,'丫丫的陪玩日记');assert.equal(desktop.features,8);assert.equal(desktop.steps,16);assert.equal(desktop.images,16);assert.ok(desktop.link.endsWith('/downloads/YayaDiary-1.2.0-Portable.zip'));assert.equal(desktop.overflow,false);assert.equal(desktop.brand,true)
  fs.writeFileSync(path.join(output,'desktop.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("document.querySelector('[data-download]').click()");assert.equal(await win.webContents.executeJavaScript("document.querySelector('#download-status').textContent.includes('尚未发布')"),true)
  win.setSize(390,844);await win.webContents.executeJavaScript("scrollTo({top:0,behavior:'instant'})");await new Promise(r=>setTimeout(r,300));const mobile=await check();assert.equal(mobile.overflow,false);fs.writeFileSync(path.join(output,'mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("document.querySelector('#tutorial').scrollIntoView({behavior:'instant'});true");await new Promise(r=>setTimeout(r,600));fs.writeFileSync(path.join(output,'mobile-tutorial.png'),(await win.webContents.capturePage()).toPNG())
  assert.deepEqual(errors,[]);console.log(JSON.stringify({desktop,mobile,errors},null,2));win.destroy();app.exit(0)
}).catch(e=>{console.error(e);app.exit(1)})
